import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

test('video extraction, frame editing, packing, folder save and animated placement persist', async ({page}) => {
  test.setTimeout(60000);
  const videoFile = test.info().outputPath('walking.webm');
  execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=96x64:rate=4:duration=1','-c:v','libvpx',videoFile]);
  const video = readFileSync(videoFile);
  await page.goto('/'); await expect(page.locator('footer')).toContainText('影棚已就绪');
  await page.getByRole('button',{name:'自定义资源',exact:true}).click();
  await page.getByLabel('新分类名称').fill('人物动作');
  await page.getByRole('button',{name:'新增分类',exact:true}).click();
  const folderId = await page.getByLabel('资源分类').inputValue();
  await page.getByLabel('新分类名称').fill('人物动作');
  await page.getByRole('button',{name:'新增分类',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('分类名称已存在');
  await page.getByRole('button',{name:'制作序列帧',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'序列帧制作'});
  await dialog.getByLabel('上传视频').setInputFiles({name:'walking.webm',mimeType:'video/webm',buffer:video});
  await dialog.getByLabel('抽帧 FPS',{exact:true}).fill('4');
  await dialog.getByRole('button',{name:'开始抽帧',exact:true}).click();
  await expect(dialog.locator('.sprite-frames article')).toHaveCount(4);
  await dialog.getByLabel('启用帧 4').uncheck();
  await dialog.locator('.sprite-frames article').nth(1).getByRole('button',{name:'前移',exact:true}).click();
  await expect(dialog.locator('.sprite-frames article').first()).toContainText('0.25s');
  await dialog.getByLabel('列数（0 为自动）').fill('2');
  await dialog.getByLabel('帧间距',{exact:true}).fill('3');
  await dialog.getByRole('button',{name:'合成序列帧',exact:true}).click();
  await expect(dialog.getByRole('img',{name:'合成序列帧',exact:true})).toBeVisible();
  // Editing invalidates the packed result so stale frame order cannot be saved.
  await dialog.getByLabel('启用帧 3').uncheck();
  await expect(dialog.getByRole('button',{name:'保存到自定义分类',exact:true})).toBeDisabled();
  await dialog.getByLabel('启用帧 3').check();
  await dialog.getByRole('button',{name:'选中帧去底',exact:true}).click();
  await expect(dialog.getByLabel('序列帧状态')).toHaveText('处理完成');
  await dialog.getByRole('button',{name:'合成序列帧',exact:true}).click();
  await expect(dialog.getByRole('img',{name:'合成序列帧',exact:true})).toBeVisible();
  await dialog.getByRole('button',{name:'播放预览',exact:true}).click();
  await page.screenshot({path:'test-results/spritesheet-editor.png'});
  await dialog.getByRole('button',{name:'保存到自定义分类',exact:true}).click();
  await expect(dialog.getByLabel('序列帧状态')).toContainText('已保存到自定义分类');
  const download = page.waitForEvent('download');
  await dialog.getByRole('button',{name:'下载 JSON',exact:true}).click();
  expect((await download).suggestedFilename()).toBe('walking.json');
  page.on('dialog',d=>d.accept());
  await dialog.getByLabel('关闭资源浏览器').click();
  await page.getByRole('button',{name:'walking',exact:true}).click();
  await expect(page.getByLabel('元素名称',{exact:true})).toHaveValue('walking');
  const canvas=page.getByLabel('影棚预览');
  const first=await canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL());
  await expect.poll(()=>canvas.evaluate((c:HTMLCanvasElement)=>c.toDataURL())).not.toBe(first);
  await page.reload(); await expect(page.locator('footer')).toContainText('影棚已就绪');
  await page.getByRole('button',{name:'自定义资源',exact:true}).click();
  await page.getByLabel('资源分类').selectOption(folderId);
  await expect(page.getByRole('button',{name:'walking',exact:true})).toBeVisible();
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('yuanli.web-director.v1')!));
  expect(stored.assets[0]).toMatchObject({customCategoryId:folderId,columns:2,rows:2});
  expect(stored.assets[0].frameRects).toHaveLength(3);
  expect(stored.assets[0].frameRects[1].x).toBe(103);
});
