import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn, execFileSync } from 'node:child_process';
import { createHmac } from 'node:crypto';
import { mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { chromium, expect } from '@playwright/test';

test('local production server saves binary media to disk and keeps browser data isolated', {timeout:60000}, async()=>{
  const dir=await mkdtemp(path.join(os.tmpdir(),'yuanli-local-browser-'));
  const probe=http.createServer(); await new Promise(r=>probe.listen(0,'127.0.0.1',r)); const port=probe.address().port; await new Promise(r=>probe.close(r));
  const secret='local-browser-test-secret-000000000000000';
  const child=spawn(process.execPath,['apps/director-web/server.mjs'],{env:{...process.env,NL_MODE:'local',NL_WORKSPACE:dir,PORT:String(port),AUTH_SECRET:secret},stdio:['ignore','pipe','pipe']});
  let log=''; child.stdout.on('data',d=>{log+=d;}); child.stderr.on('data',d=>{log+=d;});
  const base=`http://127.0.0.1:${port}`;
  let browser;
  try {
    await expect.poll(()=>log,{timeout:10000}).toContain('导演台：http');
    const unauth=await fetch(base+'/api/workspace',{redirect:'manual'}); assert.equal(unauth.status,401);
    browser=await chromium.launch({args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
    const context=await browser.newContext({viewport:{width:1440,height:960}});
    const expires=String(Date.now()+3600000), signature=createHmac('sha256',secret).update(expires).digest('base64url');
    await context.addCookies([{name:'director_session',value:`${expires}.${signature}`,url:base}]);
    const page=await context.newPage();
    await page.goto(base); await expect(page.locator('.badge')).toHaveText('本地工作 · 磁盘保存');
    await expect(page.locator('footer')).toContainText('影棚已就绪');
    await expect.poll(async()=>{try{return JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).version;}catch{return 0;}}).toBe(1);
    await page.getByRole('button',{name:'自定义资源',exact:true}).click();
    await page.getByLabel('资源分类').selectOption('characters');
    const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=32;c.height=32;c.getContext('2d').fillRect(0,0,32,32);return c.toDataURL().split(',')[1];});
    await page.getByLabel('上传自定义资源').setInputFiles({name:'disk.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
    await page.getByRole('button',{name:'disk.png',exact:true}).click();
    await expect(page.getByLabel('元素名称',{exact:true})).toHaveValue('disk.png');
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).assets.length).toBe(1);
    const stored=JSON.parse(await readFile(path.join(dir,'project.json'),'utf8'));
    assert.match(stored.assets[0].src,/^media\/[a-f0-9]{64}\.png$/);
    assert.equal((await readFile(path.join(dir,stored.assets[0].src))).toString('base64'),png);
    assert.ok(!JSON.stringify(stored).includes('base64'));
    const downloading=page.waitForEvent('download'); await page.getByRole('button',{name:'导出项目',exact:true}).click();
    const downloaded=await downloading;
    const portable=JSON.parse(await readFile(await downloaded.path(),'utf8')); assert.match(portable.assets[0].src,/^data:image\/png;base64,/);
    // The production workflow retains original video + edited frames + output,
    // without needing the original file picker selection after a reload.
    const videoPath=path.join(dir,'test-walk.webm');
    execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','testsrc2=size=96x64:rate=4:duration=1','-c:v','libvpx',videoPath]);
    const video=await readFile(videoPath);
    await page.getByLabel('新分类名称').fill('动作草稿');await page.getByRole('button',{name:'新增分类',exact:true}).click();
    await page.getByRole('button',{name:'制作序列帧',exact:true}).click();
    let sprite=page.getByRole('dialog',{name:'序列帧制作'});
    await sprite.getByLabel('选择本地视频').setInputFiles({name:'walk.webm',mimeType:'video/webm',buffer:video});
    await sprite.getByLabel('抽帧 FPS',{exact:true}).fill('4');await sprite.getByRole('button',{name:'开始抽帧',exact:true}).click();
    await expect(sprite.locator('.sprite-frames article')).toHaveCount(4);
    await sprite.getByLabel('启用帧 4').uncheck();
    await sprite.locator('.sprite-frames article').nth(1).getByRole('button',{name:'前移',exact:true}).click();
    await sprite.getByRole('button',{name:'选中帧去底',exact:true}).click();
    await expect(sprite.getByLabel('序列帧状态')).toHaveText('处理完成');
    await sprite.getByLabel('帧间距',{exact:true}).fill('3');await sprite.getByLabel('播放 FPS',{exact:true}).fill('8');
    await sprite.getByRole('button',{name:'合成序列帧',exact:true}).click();
    await expect(sprite.getByRole('img',{name:'合成序列帧',exact:true})).toBeVisible();
    await sprite.getByRole('button',{name:'保存制作草稿到磁盘',exact:true}).click();
    await expect(sprite.getByLabel('序列帧状态')).toContainText('制作草稿已保存到本地磁盘');
    const draft=JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).spriteDrafts[0];
    assert.deepEqual(await readFile(path.join(dir,draft.source.src)),video);
    assert.equal(draft.frames[0].time,0.25);assert.equal(draft.frames[3].enabled,false);assert.ok(draft.frames.some(f=>f.cutout));
    assert.equal(draft.fps,8);assert.equal(draft.pack.spacing,3);assert.ok(draft.output.src.startsWith('media/'));
    for(const f of draft.frames) assert.ok((await readFile(path.join(dir,f.src))).length);
    // Save failures must not claim success or lose the working selection; retry
    // should work from inside the modal without refreshing the whole editor.
    await sprite.getByLabel('序列帧名称').fill('walk-saved');
    await page.route('**/api/workspace/project',r=>r.request().method()==='PUT'?r.abort():r.continue());
    await sprite.getByRole('button',{name:'保存制作草稿到磁盘',exact:true}).click();
    await expect(sprite.getByLabel('序列帧状态')).toContainText('草稿保存失败');
    await page.unroute('**/api/workspace/project');
    await sprite.getByRole('button',{name:'保存制作草稿到磁盘',exact:true}).click();
    await expect(sprite.getByLabel('序列帧状态')).toContainText('制作草稿已保存到本地磁盘');
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).spriteDrafts[0].name).toBe('walk-saved');
    await expect(page.getByRole('button',{name:/^本地文件 · 已保存/})).toBeVisible();
    await sprite.getByLabel('关闭资源浏览器').click();
    await page.evaluate(()=>localStorage.clear()); await page.reload(); await expect(page.locator('footer')).toContainText('影棚已就绪');
    await expect(page.getByRole('button',{name:'♙ disk.png',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'自定义资源',exact:true}).click();await page.getByRole('button',{name:'制作序列帧',exact:true}).click();
    sprite=page.getByRole('dialog',{name:'序列帧制作'});
    await sprite.getByLabel('已有制作草稿').selectOption(draft.id);await sprite.getByRole('button',{name:'打开制作草稿',exact:true}).click();
    await expect(sprite.getByLabel('序列帧状态')).toContainText('已读取本地草稿');
    await expect(sprite.locator('.sprite-frames article')).toHaveCount(4);await expect(sprite.locator('.sprite-frames article').first()).toContainText('0.25s');
    await expect(sprite.getByLabel('启用帧 4')).not.toBeChecked();await expect(sprite.getByLabel('播放 FPS',{exact:true})).toHaveValue('8');
    await expect(sprite.getByLabel('帧间距',{exact:true})).toHaveValue('3');await expect(sprite.getByRole('img',{name:'合成序列帧',exact:true})).toBeVisible();
    await sprite.getByRole('button',{name:'保存到自定义分类',exact:true}).click();
    await expect(sprite.getByLabel('序列帧状态')).toContainText('原视频、制作草稿与成品均已落盘');
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).assets.length).toBe(2);
    await expect(page.getByRole('button',{name:/^本地文件 · 已保存/})).toBeVisible();
    await page.screenshot({path:'test-results/local-sprite-draft.png'});
    await sprite.getByLabel('关闭资源浏览器').click();
    // Auth expiry must preserve edits and keep the unload guard active after failure.
    await context.clearCookies();
    await page.getByLabel('布景名称',{exact:true}).fill('登录过期时的修改');
    await expect(page.locator('.workspace-warning')).toContainText('登录已过期');
    assert.equal(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented;}),true);
    await context.addCookies([{name:'director_session',value:`${expires}.${signature}`,url:base}]);
    await page.locator('.workspace-warning').getByRole('button',{name:'重试保存',exact:true}).click();
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).shots[0].name).toBe('登录过期时的修改');
    await expect(page.locator('.workspace-warning')).toHaveCount(0);
    // A transient network failure leaves an IndexedDB draft recoverable on reload.
    await page.route('**/api/workspace/project',route=>route.request().method()==='PUT'?route.abort():route.continue());
    await page.getByLabel('布景名称',{exact:true}).fill('从恢复草稿找回');
    await expect(page.locator('.workspace-warning')).toBeVisible();
    await page.unroute('**/api/workspace/project');
    const recoverDialogs=d=>d.accept(); page.on('dialog',recoverDialogs); await page.reload();
    await expect(page.getByLabel('布景名称',{exact:true})).toHaveValue('从恢复草稿找回');
    page.off('dialog',recoverDialogs);
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).shots[0].name).toBe('从恢复草稿找回');
    // Exercise binary package UI without the platform file picker in automation.
    await page.evaluate(()=>Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true}));
    await page.getByRole('button',{name:/^本地文件 · 已保存/}).click();
    const packDownload=page.waitForEvent('download'); await page.getByRole('button',{name:'导出项目包',exact:true}).click();
    const pack=await packDownload, packed=await readFile(await pack.path()); assert.equal(packed.subarray(0,12).toString(),'project.json');
    await expect(page.getByRole('dialog').getByRole('status')).toContainText('项目包已导出');
    await page.screenshot({path:'test-results/local-files-panel.png'});
    await page.getByRole('button',{name:'关闭本地文件',exact:true}).click();
    await page.getByLabel('布景名称',{exact:true}).fill('导入前的新内容');
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).shots[0].name).toBe('导入前的新内容');
    await page.getByRole('button',{name:/^本地文件 · 已保存/}).click();page.once('dialog',d=>d.accept());
    await page.getByLabel('导入项目包',{exact:true}).setInputFiles({name:'roundtrip.nlpack',mimeType:'application/octet-stream',buffer:packed});
    await expect(page.getByRole('dialog').getByRole('status')).toContainText('项目包已导入');
    await page.getByRole('button',{name:'关闭本地文件',exact:true}).click();
    await expect(page.getByLabel('布景名称',{exact:true})).toHaveValue('从恢复草稿找回');
    const other=await context.newPage(); await other.goto(base); await expect(other.locator('footer')).toContainText('影棚已就绪');
    await page.getByLabel('布景名称',{exact:true}).fill('窗口一');
    await expect.poll(async()=>JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).shots[0].name).toBe('窗口一');
    await other.getByLabel('布景名称',{exact:true}).fill('冲突修改'); await expect(other.locator('footer')).toContainText('项目已被其他窗口修改');
    assert.equal(JSON.parse(await readFile(path.join(dir,'project.json'),'utf8')).shots[0].name,'窗口一');
    await other.close();
    await page.getByRole('button',{name:'本机备份',exact:true}).click(); await expect(page.getByRole('dialog',{name:'本机备份管理'})).toContainText('backups');
    await page.screenshot({path:'test-results/local-work.png'});
    await writeFile(path.join(dir,'project.json'),'broken'); await page.reload();
    await expect(page.getByRole('alert')).toContainText('已禁止自动覆盖');
    assert.equal(await readFile(path.join(dir,'project.json'),'utf8'),'broken');
  } finally {
    await browser?.close();
    const exited=new Promise(resolve=>child.once('exit',resolve)); child.kill('SIGTERM'); await exited;
    await rm(dir,{recursive:true,force:true});
  }
});
