import { z } from 'zod';
import { nlAssets } from './nl-assets';
export const mediaSchema = z.object({ id: z.string(), name: z.string().min(1), customCategoryId: z.string().optional(), frameRects: z.array(z.object({ x: z.number().int().min(0), y: z.number().int().min(0), width: z.number().int().positive(), height: z.number().int().positive() })).min(1).max(120).optional(), category: z.enum(['backgrounds', 'trees', 'characters', 'houses', 'audio', 'models']), src: z.string().max(30_000_000).regex(/^(\/art\/[a-z0-9_]+\.png|data:(image\/(png|jpeg|webp)|audio\/[a-z0-9.+-]+|model\/gltf-binary);base64,[A-Za-z0-9+/=]+)$/), width: z.number().min(1).max(8192).default(1), height: z.number().min(1).max(8192).default(1), columns: z.number().int().min(1).max(64).default(1), rows: z.number().int().min(1).max(64).default(1), fps: z.number().min(0.1).max(60).default(12) }).refine(a => !a.frameRects || a.frameRects.every(r => r.x + r.width <= a.width && r.y + r.height <= a.height), "序列帧范围超出图片");
export type MediaAsset = z.infer<typeof mediaSchema>;
const dimensions: Record<string, [number, number]> = { legacy_village: [1152,864], bridge_stone: [265,153], cart: [215,180], coop: [298,213], crates_still_life: [220,176], flowers_blue: [172,156], flowers_pink: [182,155], flowers_white_a: [162,136], flowers_white_b: [167,141], garden_plot: [316,198], house_blue_cottage: [271,239], house_market: [273,238], house_round_green: [224,240], house_watermill: [296,255], lamppost: [125,192], signboard: [160,181], tree_cherry: [219,222], tree_oak: [276,234], tree_pine: [179,230], well: [205,208], windmill: [205,227] };
export const builtinAssets: MediaAsset[] = [
  ['legacy_village', '旧版示例村庄', 'backgrounds'],
  ['player', '农夫', 'characters'], ['farmer_blue', '蓝衣农夫', 'characters'], ['tree_oak', '橡树', 'trees'], ['tree_pine', '松树', 'trees'], ['tree_cherry', '樱树', 'trees'], ['house_blue_cottage', '蓝顶小屋', 'houses'], ['house_market', '集市', 'houses'], ['house_round_green', '绿顶圆屋', 'houses'], ['house_watermill', '水车屋', 'houses'], ['bridge_stone', '石桥', 'houses'], ['cart', '木车', 'houses'], ['well', '水井', 'houses'], ['lamppost', '路灯', 'houses'],
  ['windmill', '风车', 'houses'], ['coop', '鸡舍', 'houses'], ['signboard', '路牌', 'houses'], ['garden_plot', '菜地', 'houses'], ['crates_still_life', '木箱', 'houses'], ['flowers_white_a', '白花甲', 'trees'], ['flowers_white_b', '白花乙', 'trees'], ['flowers_blue', '蓝花', 'trees'], ['flowers_pink', '粉花', 'trees'],
].map(([id, name, category]) => mediaSchema.parse({ id, name, category, src: `/art/${id === 'farmer_blue' ? 'player' : id}.png`, width: dimensions[id]?.[0] ?? 82, height: dimensions[id]?.[1] ?? 119 }));
builtinAssets.push(...nlAssets);
export const audioTrackSchema = z.object({ id: z.string(), name: z.string(), assetId: z.string(), startFrame: z.number().int().min(0).max(180000), offsetFrame: z.number().int().min(0).max(180000).default(0), frames: z.number().int().min(1).max(180000), volume: z.number().min(0).max(1).default(1), muted: z.boolean().default(false) });
export const object3dSchema = z.object({ id: z.string(), name: z.string().min(1), shape: z.enum(['box', 'sphere', 'cylinder', 'plane', 'model']), assetId: z.string().nullable().default(null), x: z.number().min(-100).max(100).default(0), y: z.number().min(-100).max(100).default(0.5), z: z.number().min(-100).max(100).default(0), scale: z.number().min(0.01).max(100).default(1), rotation: z.number().default(0), spin: z.number().min(-360).max(360).default(0), color: z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#79b6ad') });
