import type { MediaAsset } from './media';

// Original NL-UI artwork; prop sheets retain their original background and layout.
export const nlAssets: MediaAsset[] = [
  {
    "id": "nl_ground_fields",
    "name": "东南小村 · 农田地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_fields.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_village_main",
    "name": "东南小村 · 村庄主区地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_village_main.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_school_path",
    "name": "东南小村 · 上学路地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_school_path.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_village_gate",
    "name": "东南小村 · 村口地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_village_gate.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_home_yard",
    "name": "东南小村 · 家门前院落地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_home_yard.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_riverside_school",
    "name": "东南小村 · 溪边学堂地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_riverside_school.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_protagonist_house",
    "name": "东南小村 · 主角家",
    "category": "houses",
    "src": "/art/nl_asset_protagonist_house.png",
    "width": 1254,
    "height": 1254,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_storage_shed",
    "name": "东南小村 · 柴房储物棚",
    "category": "houses",
    "src": "/art/nl_asset_storage_shed.png",
    "width": 1380,
    "height": 1140,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_cart_tools",
    "name": "东南小村 · 推车农具素材整图",
    "category": "houses",
    "src": "/art/nl_asset_cart_tools.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_villager_houses",
    "name": "东南小村 · 村民房屋素材整图",
    "category": "houses",
    "src": "/art/nl_asset_villager_houses.png",
    "width": 1448,
    "height": 1086,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_livestock_coop",
    "name": "东南小村 · 畜栏鸡舍素材整图",
    "category": "houses",
    "src": "/art/nl_asset_livestock_coop.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_school",
    "name": "东南小村 · 学堂",
    "category": "houses",
    "src": "/art/nl_asset_school.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_gate_fence",
    "name": "东南小村 · 木桩矮篱素材整图",
    "category": "houses",
    "src": "/art/nl_asset_gate_fence.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_well",
    "name": "东南小村 · 水井",
    "category": "houses",
    "src": "/art/nl_asset_well.png",
    "width": 1254,
    "height": 1254,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_bridge",
    "name": "东南小村 · 桥梁",
    "category": "houses",
    "src": "/art/nl_asset_bridge.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_crop_patches",
    "name": "东南小村 · 作物地块素材整图",
    "category": "houses",
    "src": "/art/nl_asset_crop_patches.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_fence_farm",
    "name": "东南小村 · 农场篱笆素材整图",
    "category": "houses",
    "src": "/art/nl_asset_fence_farm.png",
    "width": 1448,
    "height": 1086,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_water_stones",
    "name": "东南小村 · 水岸踏石水缸素材整图",
    "category": "houses",
    "src": "/art/nl_asset_water_stones.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_nature_signs",
    "name": "东南小村 · 自然与路牌素材整图",
    "category": "houses",
    "src": "/art/nl_asset_nature_signs.png",
    "width": 1448,
    "height": 1086,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_yard_misc",
    "name": "东南小村 · 院落杂物素材整图",
    "category": "houses",
    "src": "/art/nl_asset_yard_misc.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_desert_dunes",
    "name": "沙漠 · 沙丘与沙径纯地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_desert_dunes.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_desert_oasis",
    "name": "沙漠 · 绿洲水洼纯地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_desert_oasis.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_desert_caravan",
    "name": "沙漠 · 商路与驿站落位纯地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_desert_caravan.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_far_desert_skyline",
    "name": "沙漠 · 远景沙丘天际线",
    "category": "backgrounds",
    "src": "/art/nl_far_desert_skyline.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_desert_post",
    "name": "沙漠 · 沙漠驿站/土屋（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_desert_post.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_desert_tents",
    "name": "沙漠 · 帐篷资产表（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_desert_tents.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_desert_rocks_scrub",
    "name": "沙漠 · 岩石与干灌丛（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_desert_rocks_scrub.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_desert_cart_crates",
    "name": "沙漠 · 商队车与货箱（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_desert_cart_crates.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_desert_well_markers",
    "name": "沙漠 · 水井与路标（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_desert_well_markers.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_desert_misc",
    "name": "沙漠 · 沙漠杂物与小构筑（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_desert_misc.png",
    "width": 1448,
    "height": 1086,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_mountain_trail",
    "name": "山地 · 山道与台地纯地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_mountain_trail.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_mountain_pine",
    "name": "山地 · 松林空地纯地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_mountain_pine.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_ground_mountain_stream",
    "name": "山地 · 山溪与石滩纯地皮",
    "category": "backgrounds",
    "src": "/art/nl_ground_mountain_stream.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_far_mountain_skyline",
    "name": "山地 · 远景山脉天际线",
    "category": "backgrounds",
    "src": "/art/nl_far_mountain_skyline.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_mountain_hut",
    "name": "山地 · 猎户小屋/石屋（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_mountain_hut.png",
    "width": 1774,
    "height": 887,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_mountain_post",
    "name": "山地 · 山道驿站/歇脚棚（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_mountain_post.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_mountain_pines_rocks",
    "name": "山地 · 松树与山岩（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_mountain_pines_rocks.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_mountain_bridge_water",
    "name": "山地 · 木桥与溪石道具（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_mountain_bridge_water.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_mountain_markers",
    "name": "山地 · 路标与山道设施（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_mountain_markers.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  },
  {
    "id": "nl_asset_mountain_misc",
    "name": "山地 · 山地杂物与小构筑（原始素材图）",
    "category": "houses",
    "src": "/art/nl_asset_mountain_misc.png",
    "width": 1536,
    "height": 1024,
    "columns": 1,
    "rows": 1,
    "fps": 12
  }
];
