import { useEffect, useRef } from 'react';
import { shotSchema, type Project, type Shot } from '../../../packages/core';
import { object3dSchema } from '../../../packages/core/media';
type Props = { project: Project; shot: Shot; edit: (fn: (p: Project) => void) => void; seek: (f: number) => void };
export function ProjectTree({ project, shot, edit, seek }: Props) {
  return <div className="project-tree"><h2>章节 / 场景</h2><button onClick={() => { const name = prompt('新章节名称'); if (name?.trim()) edit(p => p.chapters.push({ id: crypto.randomUUID(), name: name.trim() })); }}>新建章节</button>{project.chapters.map(c => <details open key={c.id}><summary>{c.name}</summary><div className="button-row"><button onClick={() => { const name = prompt('章节名称', c.name); if (name?.trim()) edit(p => { p.chapters.find(x => x.id === c.id)!.name = name.trim(); }); }}>改名</button><button onClick={() => { if (project.chapters.length === 1) return; if (confirm('删除章节？场景将移入第一个其他章节，可撤销。')) edit(p => { p.chapters = p.chapters.filter(x => x.id !== c.id); p.scenes.filter(s => s.chapterId === c.id).forEach(s => { s.chapterId = p.chapters[0].id; }); }); }}>删除</button><button onClick={() => { const name = prompt('场景名称'); if (!name?.trim()) return; const id = crypto.randomUUID(); edit(p => { p.scenes.push({ id, name: name.trim(), chapterId: c.id }); p.shots.push(shotSchema.parse({ id: crypto.randomUUID(), name: `${name} · 镜头1`, studio: 'pixi', sceneId: id, frames: 180, caption: '', background: 'protagonist_village', actors: [] })); }); seek(project.shots.reduce((n, s) => n + s.frames, 0)); }}>新场景</button></div>{project.scenes.filter(s => s.chapterId === c.id).map(s => <div key={s.id}><button className={shot.sceneId === s.id ? 'active row' : 'row'} onClick={() => { const index = project.shots.findIndex(x => x.sceneId === s.id); if (index >= 0) seek(project.shots.slice(0, index).reduce((n, x) => n + x.frames, 0)); }}>{s.name}</button><button onClick={() => { const name = prompt('场景名称', s.name); if (name?.trim()) edit(p => { p.scenes.find(x => x.id === s.id)!.name = name.trim(); }); }}>改名</button><button onClick={() => { if (project.scenes.length === 1 || project.shots.every(x => x.sceneId === s.id)) return; if (confirm('删除场景及其全部镜头？可撤销恢复。')) { edit(p => { p.scenes = p.scenes.filter(x => x.id !== s.id); p.shots = p.shots.filter(x => x.sceneId !== s.id); }); seek(0); } }}>删除</button></div>)}</details>)}</div>;
}
export function ExtendedInspector({ project, shot, edit, selected }: Omit<Props, 'seek'> & { selected: string }) {
  const change = (fn: (s: Shot) => void) => edit(p => fn(p.shots.find(s => s.id === shot.id)!));
  const actor = shot.actors.find(a => a.id === selected);
  return <section><h2>镜头组织</h2><label>所属场景<select value={shot.sceneId} onChange={e => change(s => { s.sceneId = e.target.value; })}>{project.scenes.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>场景所在章节<select value={project.scenes.find(s => s.id === shot.sceneId)?.chapterId} onChange={e => edit(p => { p.scenes.find(s => s.id === shot.sceneId)!.chapterId = e.target.value; })}>{project.chapters.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>影棚<select value={shot.studio} onChange={e => change(s => { s.studio = e.target.value as Shot['studio']; })}><option value="pixi">2D</option><option value="motion">动态图形</option><option value="three">3D / PlayCanvas</option></select></label><button onClick={() => edit(p => { const version = p.sets.filter(s => s.name === shot.name).length + 1; p.sets.push({ id: crypto.randomUUID(), name: shot.name, version, content: structuredClone(shot) }); })}>保存布景版本</button><label>从布景版本新建镜头<select value="" onChange={e => { const set = project.sets.find(s => s.id === e.target.value); if (set) edit(p => { const copy = structuredClone(set.content); copy.id = crypto.randomUUID(); copy.sceneId = shot.sceneId; copy.setRef = set.id; p.shots.push(copy); }); }}><option value="">选择不可变快照…</option>{project.sets.map(s => <option key={s.id} value={s.id}>{s.name} · v{s.version}</option>)}</select></label>
    {shot.studio === 'pixi' && <><label className="check"><input type="checkbox" checked={shot.collisionEnabled} onChange={e => change(s => { s.collisionEnabled = e.target.checked; })}/>全局区域碰撞</label><label>吸附网格（0 为关闭）<input type="number" min="0" max="128" value={shot.snap} onChange={e => change(s => { s.snap = Number(e.target.value); })}/></label><label className="check"><input type="checkbox" checked={shot.wind.enabled} onChange={e => change(s => { s.wind.enabled = e.target.checked; })}/>启用风迹</label><label>全局风向强度<input type="range" min="-1" max="1" step="0.05" value={shot.wind.strength} onChange={e => change(s => { s.wind.strength = Number(e.target.value); })}/></label><label>风迹速度<input type="range" min="0" max="4" step="0.1" value={shot.wind.speed} onChange={e => change(s => { s.wind.speed = Number(e.target.value); })}/></label><label className="check"><input type="checkbox" checked={shot.lightning.enabled} onChange={e => change(s => { s.lightning.enabled = e.target.checked; })}/>启用闪电</label><label>闪电间隔（秒）<input type="number" min="1" max="60" value={shot.lightning.interval} onChange={e => change(s => { s.lightning.interval = Number(e.target.value); })}/></label><label>闪电强度<input type="range" min="0" max="1" step="0.05" value={shot.lightning.intensity} onChange={e => change(s => { s.lightning.intensity = Number(e.target.value); })}/></label></>}
    {actor && <><h2>变换 / 路线</h2>{(['scale', 'rotation', 'width', 'height', 'speed'] as const).map(key => <label key={key}>{({ scale: '缩放比例', rotation: '旋转角度', width: '元素宽度', height: '元素高度', speed: '路线速度（像素/秒）' })[key]}<input type="number" value={actor[key]} onChange={e => change(s => { s.actors.find(a => a.id === actor.id)![key] = Number(e.target.value); })}/></label>)}{(['enabled', 'flipX', 'flipY', 'loop', 'routeVisible'] as const).map(key => <label className="check" key={key}><input type="checkbox" checked={actor[key]} onChange={e => change(s => { s.actors.find(a => a.id === actor.id)![key] = e.target.checked; })}/>{({ enabled: '显示元素', flipX: '水平镜像', flipY: '垂直镜像', loop: '路线循环', routeVisible: '显示路线' })[key]}</label>)}<label>路线碰撞<select value={actor.collision} onChange={e => change(s => { s.actors.find(a => a.id === actor.id)!.collision = e.target.value as 'stop' | 'ignore'; })}><option value="ignore">忽略</option><option value="stop">遇到区域停止</option></select></label><label className="check"><input type="checkbox" checked={actor.sortY !== null} onChange={e => change(s => { s.actors.find(a => a.id === actor.id)!.sortY = e.target.checked ? actor.start.y : null; })}/>元素遮挡横线</label>{actor.sortY !== null && <label>元素遮挡 Y<input type="number" value={actor.sortY} onChange={e => change(s => { s.actors.find(a => a.id === actor.id)!.sortY = Number(e.target.value); })}/></label>}{actor.route.map((p, i) => <fieldset key={i}><legend>路线点 {i + 1}</legend>{(['x', 'y'] as const).map(axis => <label key={axis}>{axis}<input type="number" value={p[axis]} onChange={e => change(s => { s.actors.find(a => a.id === actor.id)!.route[i][axis] = Number(e.target.value); })}/></label>)}<button onClick={() => change(s => { s.actors.find(a => a.id === actor.id)!.route.splice(i, 1); })}>移除</button></fieldset>)}<button onClick={() => change(s => { s.actors.find(a => a.id === actor.id)!.route = []; })}>清除路线</button><button onClick={() => change(s => { const a = structuredClone(actor); a.id = crypto.randomUUID(); a.name += ' 副本'; s.actors.push(a); })}>复制元素</button><button onClick={() => change(s => { s.actors = s.actors.filter(a => a.id !== actor.id); })}>删除图片元素</button></>}
    {shot.studio === 'motion' && <><label>动效标题<input value={shot.motionTitle} onChange={e => change(s => { s.motionTitle = e.target.value; })}/></label>{shot.motionLabels.map((text, i) => <label key={i}>节点 {i + 1}<input value={text} onChange={e => change(s => { s.motionLabels[i] = e.target.value; })}/></label>)}</>}
    {shot.studio === 'three' && <><h2>3D 布景</h2><label>添加几何体<select value="" onChange={e => { if (e.target.value) change(s => s.objects3d.push(object3dSchema.parse({ id: crypto.randomUUID(), name: e.target.value, shape: e.target.value }))); }}><option value="">选择…</option>{['box', 'sphere', 'cylinder', 'plane'].map(shape => <option key={shape}>{shape}</option>)}</select></label>{shot.objects3d.map(object => <details key={object.id} open={selected === object.id}><summary>{object.name}</summary><label>物体名称<input value={object.name} onChange={e => change(s => { s.objects3d.find(o => o.id === object.id)!.name = e.target.value; })}/></label>{(['x', 'y', 'z', 'scale', 'rotation', 'spin'] as const).map(key => <label key={key}>{key}<input type="number" value={object[key]} onChange={e => change(s => { s.objects3d.find(o => o.id === object.id)![key] = Number(e.target.value); })}/></label>)}<input disabled={object.shape === 'model'} aria-label="3D 颜色" type="color" value={object.color} onChange={e => change(s => { s.objects3d.find(o => o.id === object.id)!.color = e.target.value; })}/><button onClick={() => change(s => { s.objects3d = s.objects3d.filter(o => o.id !== object.id); })}>删除物体</button></details>)}<h2>3D 相机</h2>{(['x', 'y', 'z', 'targetY', 'fov'] as const).map(key => <label key={key}>相机 {key}<input type="number" value={shot.camera3d[key]} onChange={e => change(s => { s.camera3d[key] = Number(e.target.value); })}/></label>)}</>}
    <h2>定时字幕</h2><button onClick={() => change(s => s.subtitles.push({ id: crypto.randomUUID(), start: 0, end: Math.min(s.frames, 90), text: '新字幕' }))}>添加字幕段</button>{shot.subtitles.map(sub => <fieldset className="subtitle-fields" key={sub.id}><input aria-label="字幕段文本" value={sub.text} onChange={e => change(s => { s.subtitles.find(t => t.id === sub.id)!.text = e.target.value; })}/>{(['start', 'end'] as const).map(key => <label key={key}>{key === 'start' ? '起始帧' : '结束帧'}<input type="number" value={sub[key]} onChange={e => change(s => { s.subtitles.find(t => t.id === sub.id)![key] = Number(e.target.value); })}/></label>)}<button onClick={() => change(s => { s.subtitles = s.subtitles.filter(t => t.id !== sub.id); })}>删除字幕</button></fieldset>)}
  </section>;
}
export function AudioPanel({ project, edit }: Pick<Props, 'project' | 'edit'>) {
  return <section><h2>音轨（全片帧坐标）</h2><p className="muted">从自定义资源上传音频，点击音频资源添加音轨。</p>{project.audioTracks.map(t => <details key={t.id}><summary>{t.name}</summary>{(['startFrame', 'offsetFrame', 'frames', 'volume'] as const).map(key => <label key={key}>{({ startFrame: '时间轴起点', offsetFrame: '音源入点', frames: '持续帧数', volume: '音量' })[key]}<input type="number" value={t[key]} onChange={e => edit(p => { p.audioTracks.find(a => a.id === t.id)![key] = Number(e.target.value); })}/></label>)}<label className="check"><input type="checkbox" checked={t.muted} onChange={e => edit(p => { p.audioTracks.find(a => a.id === t.id)!.muted = e.target.checked; })}/>静音</label><button onClick={() => edit(p => { p.audioTracks = p.audioTracks.filter(a => a.id !== t.id); })}>删除音轨</button></details>)}</section>;
}
export function useAudio(project: Project, frame: number, playing: boolean) {
  const refs = useRef(new Map<string, HTMLAudioElement>());
  useEffect(() => () => { refs.current.forEach(a => a.pause()); refs.current.clear(); }, []);
  useEffect(() => {
    const active = new Set<string>();
    for (const track of project.audioTracks) {
      const media = project.assets.find(a => a.id === track.assetId); if (!media) continue; active.add(track.id);
      let audio = refs.current.get(track.id); if (!audio || audio.src !== media.src) { audio?.pause(); audio = new Audio(media.src); refs.current.set(track.id, audio); }
      audio.volume = Math.min(1, track.volume);
      if (!playing || track.muted || frame < track.startFrame || frame >= track.startFrame + track.frames) audio.pause();
      else { const time = (frame - track.startFrame + track.offsetFrame) / 30; if (Math.abs(audio.currentTime - time) > 0.15) audio.currentTime = time; if (audio.paused) audio.play().catch(() => {}); }
    }
    refs.current.forEach((audio, id) => { if (!active.has(id)) { audio.pause(); refs.current.delete(id); } });
  }, [project, frame, playing]);
}
