import { useState } from 'react';
import { actorSchema, type Project, type Shot } from '../../../packages/core';
import { builtinAssets, object3dSchema, type MediaAsset } from '../../../packages/core/media';
import { importMedia } from './storage';
export function ResourceLibrary({ project, shot, edit, select, notify }: { project: Project; shot: Shot; edit: (fn: (p: Project) => void) => void; select: (id: string) => void; notify: (s: string) => void }) {
  const [custom, setCustom] = useState(false), [category, setCategory] = useState<MediaAsset['category']>('trees'), [search, setSearch] = useState('');
  async function place(asset: MediaAsset) {
    if (asset.category === 'models') { if (shot.studio !== 'three') { notify('模型请放入 3D 镜头'); return; } edit(p => p.shots.find(s => s.id === shot.id)!.objects3d.push(object3dSchema.parse({ id: crypto.randomUUID(), name: asset.name, shape: 'model', assetId: asset.id }))); return; }
    if (asset.category === 'audio') { edit(p => { p.audioTracks.push({ id: crypto.randomUUID(), name: asset.name, assetId: asset.id, startFrame: 0, offsetFrame: 0, frames: 180, volume: 1, muted: false }); }); return; }
    if (shot.studio !== 'pixi') { notify('图片资源请放入 2D 镜头'); return; }
    if (asset.category === 'backgrounds') { if (!confirm('当前已有背景，是否替换？元素坐标将保留。')) return; edit(p => { const s = p.shots.find(s => s.id === shot.id)!; s.backgroundAssetId = asset.id; s.backgroundVersions = {}; s.blank = false; }); return; }
    const image = new Image(); image.src = asset.src; await image.decode();
    const id = crypto.randomUUID(), height = asset.category === 'characters' ? 119 : 250, width = height * (image.naturalWidth / asset.columns) / (image.naturalHeight / asset.rows);
    edit(p => { p.shots.find(s => s.id === shot.id)!.actors.push(actorSchema.parse({ id, name: asset.name, assetId: asset.id, width, height, start: { x: 768, y: 450 }, end: { x: 768, y: 450 } })); }); select(id);
  }
  return <section className="resources"><h2>资源库</h2><div className="button-row"><button className={!custom ? 'active' : ''} onClick={() => setCustom(false)}>默认资源</button><button className={custom ? 'active' : ''} onClick={() => setCustom(true)}>自定义资源</button></div><label>资源分类<select value={category} onChange={e => setCategory(e.target.value as typeof category)}>{Object.entries({ backgrounds: '背景图', trees: '树木', characters: '角色', houses: '房屋 / 道具', audio: '音频', models: '3D 模型（GLB）' }).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><input aria-label="搜索资源" placeholder="搜索资源…" value={search} onChange={e => setSearch(e.target.value)}/>{custom && <label className="button">上传{category === 'audio' ? '音频' : '图片'}<input aria-label="上传自定义资源" type="file" hidden accept={category === 'audio' ? 'audio/*' : category === 'models' ? '.glb' : 'image/png,image/jpeg,image/webp'} multiple onChange={async e => { const files = [...(e.target.files ?? [])]; e.target.value = ''; try { const assets = await Promise.all(files.map(f => importMedia(f, category))); if (JSON.stringify(project.assets).length + JSON.stringify(assets).length > 100_000_000) throw new Error('项目资源总量不可超过 100MB'); edit(p => { p.assets.push(...assets); }); notify('资源已上传到本机；导出项目会包含资源'); } catch (e) { notify(String(e)); } }}/></label>}
    {(custom ? project.assets : builtinAssets).filter(a => a.category === category && a.name.includes(search)).map(a => <div key={a.id}><button className="asset" onClick={() => place(a).catch(e => notify(String(e)))}>{!['audio', 'models'].includes(a.category) && <img src={a.src} alt={a.name}/>}<span>{a.name}</span></button>{custom && a.category === 'characters' && <div className="sprite-settings">{(['columns', 'rows', 'fps'] as const).map(key => <label key={key}>{({ columns: '帧列', rows: '帧行', fps: '动画 FPS' })[key]}<input type="number" min="1" max={key === 'fps' ? 60 : 64} value={a[key]} onChange={e => edit(p => { p.assets.find(asset => asset.id === a.id)![key] = Number(e.target.value); })}/></label>)}</div>}{custom && <button onClick={() => { const used = project.shots.some(s => s.backgroundAssetId === a.id || Object.values(s.backgroundVersions).includes(a.id) || (s.actors.some(actor => actor.assetId === a.id) || s.objects3d.some(o => o.assetId === a.id))) || project.audioTracks.some(t => t.assetId === a.id) || project.sets.some(s => s.content.backgroundAssetId === a.id || (s.content.actors.some(actor => actor.assetId === a.id) || s.content.objects3d.some(o => o.assetId === a.id)) || Object.values(s.content.backgroundVersions).includes(a.id)); if (used) notify('资源仍被镜头、音轨或布景引用，不能删除'); else if (confirm('删除此自定义资源？可通过撤销恢复。')) edit(p => { p.assets = p.assets.filter(asset => asset.id !== a.id); }); }}>删除资源</button>}</div>)}
    {!custom && category === 'backgrounds' && <p className="muted">内置背景及各时节请使用上方背景缩略图和右侧时节面板。</p>}
  </section>;
}
